# Generated by Django 5.2.5 on 2025-09-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminMember',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('plan', models.CharField(max_length=50)),
                ('days_completed', models.IntegerField(default=0)),
                ('days_remaining', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AdminTrainer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_of_joining', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
