# Generated by Django 5.2.5 on 2025-09-30 05:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitApp', '0002_adminmember_admintrainer_usertable_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
