# Generated by Django 5.2.6 on 2025-09-30 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitApp', '0002_adminmember_admintrainer_usertable_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminmember',
            name='days_completed',
        ),
        migrations.RemoveField(
            model_name='adminmember',
            name='days_remaining',
        ),
        migrations.AddField(
            model_name='adminmember',
            name='date_of_joining',
            field=models.DateField(blank=True, null=True),
        ),
    ]
