# Generated by Django 5.2.5 on 2025-09-30 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitApp', '0003_usertable_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminmember',
            name='days_completed',
        ),
        migrations.RemoveField(
            model_name='adminmember',
            name='days_remaining',
        ),
        migrations.AddField(
            model_name='adminmember',
            name='date_of_joining',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='admintrainer',
            name='date_of_joining',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
