# Generated by Django 5.2.6 on 2025-09-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialization', models.CharField(blank=True, max_length=100)),
                ('experience', models.IntegerField(default=0)),
            ],
        ),
    ]
