# Generated by Django 5.2.6 on 2025-09-30 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bmi',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='bmi',
            name='height',
            field=models.FloatField(default=1.0, help_text='Height in meters'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bmi',
            name='weight',
            field=models.FloatField(default=1, help_text='Weight in kg'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bmi',
            name='bmi_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bmi',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('plan_name', models.CharField(max_length=100)),
                ('breakfast', models.TextField(blank=True)),
                ('lunch', models.TextField(blank=True)),
                ('dinner', models.TextField(blank=True)),
                ('snacks', models.TextField(blank=True)),
                ('calories', models.FloatField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
